<?php
define('NOVA_APP', true); require_once 'includes/config.php'; require_once 'includes/db.php'; require_once 'includes/functions.php'; require_once 'includes/auth.php';
requireLogin(); $user = currentUser(); if (!$user) { logout(); redirect(SITE_URL . '/login.php'); }
$stmt=$pdo->prepare("SELECT COUNT(*) FROM enrollments WHERE user_id=?"); $stmt->execute([$user['id']]); $enrollCount=$stmt->fetchColumn();
$stmt=$pdo->prepare("SELECT COUNT(*) FROM enrollments WHERE user_id=? AND status='completed'"); $stmt->execute([$user['id']]); $completedCount=$stmt->fetchColumn();
$stmt=$pdo->prepare("SELECT c.title,c.image,e.status FROM enrollments e JOIN courses c ON c.id=e.course_id WHERE e.user_id=? ORDER BY e.created_at DESC LIMIT 3"); $stmt->execute([$user['id']]); $recentCourses=$stmt->fetchAll();
$pageTitle='لوحة التعلم — '.SITE_NAME; require_once 'includes/header.php';
?>
<div class="container learner-shell"><div class="learner-grid"><aside class="learner-nav"><div class="learner-nav-head"><span>✦</span><div><strong>مساحة التعلم</strong><small>NOVA LEARNING</small></div></div><nav><a href="dashboard.php" class="active"><i>⌂</i> نظرة عامة</a><a href="my-courses.php"><i>▣</i> دوراتي</a><a href="courses.php"><i>＋</i> اكتشف الدورات</a><a href="profile.php"><i>◉</i> ملفي الشخصي</a></nav><div class="learner-nav-bottom"><a href="logout.php"><i>↪</i> تسجيل الخروج</a></div></aside><main class="learner-main"><div class="learner-topbar"><div><span class="v2-overline">LEARNING DASHBOARD</span><h1>مرحباً، <?= clean($user['full_name']) ?> <span>✦</span></h1><p>استمر في بناء مستقبلك، خطوة تعلم واحدة في كل مرة.</p></div><a href="profile.php" class="learner-avatar"><?= mb_substr($user['full_name'],0,1) ?></a></div><section class="learner-banner"><div><span>مساحتك الخاصة للتقدم</span><h2>كل إنجاز صغير<br><em>يصنع فرقاً كبيراً.</em></h2><a href="courses.php" class="btn btn-primary">تابع التعلم <b>←</b></a></div><div class="banner-ring"><strong><?= $enrollCount ? '68' : '0' ?><small>%</small></strong><span>متوسط تقدمك</span></div></section><div class="learner-stats"><div><span class="stat-icon purple">▣</span><strong><?= $enrollCount ?></strong><small>الدورات المسجلة</small></div><div><span class="stat-icon pink">✓</span><strong><?= $completedCount ?></strong><small>الدورات المكتملة</small></div><div><span class="stat-icon gold">✦</span><strong><?= date('Y',strtotime($user['created_at'])) ?></strong><small>سنة الانضمام</small></div></div><section class="learner-courses"><div class="learner-section-head"><div><span class="v2-overline">CONTINUE LEARNING</span><h2>تابع من حيث توقفت</h2></div><a href="my-courses.php">كل دوراتي ←</a></div><?php if ($recentCourses): ?><div class="learner-course-list"><?php foreach($recentCourses as $rc): ?><a href="my-courses.php" class="learner-course-item"><div class="learner-course-thumb"><?php if($rc['image']): ?><img src="<?= SITE_URL ?>/uploads/courses/<?= rawurlencode($rc['image']) ?>" alt=""><?php else: ?>✦<?php endif; ?></div><div><strong><?= clean($rc['title']) ?></strong><small><?= $rc['status']==='completed'?'مكتملة':'مسجلة للتعلم' ?></small><div class="mini-progress"><i style="width:<?= $rc['status']==='completed'?100:68 ?>%"></i></div></div><b>←</b></a><?php endforeach; ?></div><?php else: ?><div class="learner-empty">لم تسجل في دورة بعد — <a href="courses.php">اكتشف الدورات الآن</a></div><?php endif; ?></section></main></div></div>
<?php require_once 'includes/footer.php'; ?>
