<?php
define('NOVA_APP', true);
require_once 'includes/config.php'; require_once 'includes/db.php'; require_once 'includes/functions.php'; require_once 'includes/auth.php';
$courses = $pdo->query("SELECT c.*, cat.name AS cat_name FROM courses c LEFT JOIN categories cat ON cat.id = c.category_id WHERE c.is_active = 1 ORDER BY c.id DESC LIMIT 3")->fetchAll();
$categories = $pdo->query("SELECT * FROM categories LIMIT 4")->fetchAll();
$pageTitle = 'مستقبل تعلمك يبدأ هنا — ' . SITE_NAME;
require_once 'includes/header.php';
?>
<div class="nova-home nova-home-v2">
<section class="v2-hero"><div class="container v2-hero-grid"><div class="v2-hero-copy"><span class="v2-label"><i></i> تعلّم بشكل مختلف</span><h1>ابنِ مهارتك.<br><span>اصنع مستقبلك.</span></h1><p>منصة تعليمية عربية تمنحك المعرفة والأدوات والمسار الواضح لتنتقل من الفضول إلى الاحتراف.</p><div class="v2-actions"><a href="courses.php" class="btn btn-primary btn-lg">ابدأ التعلم الآن <b>←</b></a><a href="about.php" class="v2-watch"><span>▶</span> اكتشف NOVA</a></div><div class="v2-rating"><strong>4.9</strong><span class="stars">★★★★★</span><small>تقييم أكثر من 1,200 متعلم</small></div></div><div class="v2-hero-art"><div class="art-grid"></div><div class="art-orb orb-one"></div><div class="art-orb orb-two"></div><div class="art-window"><div class="window-bar"><i></i><i></i><i></i><span>مساري التعليمي</span></div><div class="window-content"><small>مرحباً بك في NOVA</small><h3>تعلّم. طبّق.<br><em>تقدّم.</em></h3><div class="window-stat"><span>تقدمك هذا الأسبوع</span><b>72%</b></div><div class="window-progress"><i></i></div><div class="window-chips"><b>UX Design</b><b>Web Dev</b><b>+3</b></div></div></div><div class="art-badge badge-a">✦ محتوى عملي</div><div class="art-badge badge-b">✓ إنجاز جديد</div></div></div></section>
<section class="v2-metrics"><div class="container metrics-grid"><div><strong>+1,200</strong><span>متعلم نشط</span></div><div><strong>+24</strong><span>ساعة محتوى عملي</span></div><div><strong>4</strong><span>مسارات متخصصة</span></div><div><strong>100%</strong><span>تجربة عربية</span></div></div></section>
<section class="container v2-section"><div class="v2-section-head"><div><span class="v2-overline">LEARN WITH PURPOSE</span><h2>اختر المسار الذي يشبه طموحك</h2></div><a href="courses.php">استكشف كل المسارات <b>←</b></a></div><div class="v2-path-grid"><?php foreach ($categories as $cat): ?><a class="v2-path" href="courses.php?category=<?= (int)$cat['id'] ?>" style="--path-image:url('<?= !empty($cat['image']) ? SITE_URL . '/uploads/categories/' . rawurlencode($cat['image']) : '' ?>')"><div class="path-overlay"></div><div class="path-content"><span><?= clean($cat['icon']) ?></span><h3><?= clean($cat['name']) ?></h3><p><?= clean($cat['description'] ?? 'ابدأ رحلتك التعليمية') ?></p><b>استكشف المسار ↗</b></div></a><?php endforeach; ?></div></section>
<section class="container v2-section v2-courses"><div class="v2-section-head"><div><span class="v2-overline">CURATED LEARNING</span><h2>دورات مصممة لتصنع فرقاً</h2></div><a href="courses.php">رؤية جميع الدورات <b>←</b></a></div><div class="v2-course-row"><?php foreach ($courses as $c): ?><a href="course.php?id=<?= (int)$c['id'] ?>" class="v2-course"><div class="v2-course-image"><?php if (!empty($c['image'])): ?><img src="<?= SITE_URL ?>/uploads/courses/<?= rawurlencode($c['image']) ?>" alt="<?= clean($c['title']) ?>"><?php endif; ?><span><?= clean($c['cat_name'] ?? 'دورة') ?></span></div><div class="v2-course-body"><h3><?= clean($c['title']) ?></h3><small>◷ <?= (int)$c['duration_hours'] ?> ساعة <i>•</i> <?= levelName($c['level']) ?></small><div><strong><?= formatPrice($c['price']) ?></strong><b>التفاصيل ←</b></div></div></a><?php endforeach; ?></div></section>
<section class="container v2-cta"><div><span class="v2-overline">YOUR NEXT MOVE</span><h2>المستقبل لا ينتظر.<br>ابدأ أنت.</h2><p>حوّل وقتك إلى معرفة، ومعرفتك إلى فرصة.</p></div><a href="register.php" class="btn btn-primary btn-lg">أنشئ حسابك مجاناً <b>←</b></a></section>
</div>
<?php require_once 'includes/footer.php'; ?>
